[package]
name = "rust-proof"
version = "0.1.0"
edition = "2024"

[dependencies]
noir_rs = { git = "https://github.com/zkpassport/noir_rs.git", tag = "v1.0.0-beta.3-1", features = [
    "barretenberg",
] }

log = "0.4"        # do prostego logowania czasu
env_logger = "0.9" # inicjalizacja loggera
